Try running PHP compat tests from PHPCompatibility dev-develop
See:
- https://github.com/Automattic/vaultpress/pull/123#issuecomment-862446125
- https://github.com/Automattic/jetpack/pull/17755

diff --git a/.github/workflows/phpcompatibility-dev.yml b/.github/workflows/phpcompatibility-dev.yml
--- a/.github/workflows/phpcompatibility-dev.yml
+++ b/.github/workflows/phpcompatibility-dev.yml
@@ -1,19 +1,17 @@
-name: PHP compatibility tests
+# This Github Action is temporary, to run the development version of PHPCompatibility to test for PHP 8 issues.
+#
+# Once we're getting that by default (likely due to an upgrade of automattic/jetpack-codesniffer to pull a version of phpcompatibility/phpcompatibility-wp that pulls phpcompatibility/php-compatibility 10.0+),
+# this action and .github/files/phpcompatibility-dev-phpcs.xml should be deleted.
+
+name: PHP Compatibility Dev
 
 on: pull_request
 
 jobs:
-  compatibility:
-    name: PHP (${{ matrix.php-versions }})
+  phpcompatibility:
+    name: dev branch for PHP 8.0
     runs-on: ubuntu-latest
-    continue-on-error: ${{ matrix.experimental }}
-    timeout-minutes: 3  # Successful runs seem to take ~1 minute
-
-    strategy:
-      fail-fast: false
-      matrix:
-        php-versions: [ '5.6', '7.0', '7.2', '7.3', '7.4', '8.0' ]
-        experimental: [ false ]
+    timeout-minutes: 3 # Successful runs seem to take ~1 minute
 
     steps:
       - name: Checkout code
@@ -22,8 +20,9 @@ jobs:
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
-          php-version: ${{ matrix.php-versions }}
+          php-version: 7.4
           tools: composer
+          extensions: mysql, imagick
           coverage: none
 
       - name: Setup Node
@@ -71,6 +70,15 @@ jobs:
           # Install repo dependencies
           yarn && yarn build-php
 
-      - name: Run the compatibility tests
+      - name: Upgrade PHPCompatibility
         run: |
-          composer php:compatibility -- --report=emacs .
+          if [[ -e vendor/phpcompatibility/php-compatibility/PHPCompatibility/Sniffs/ControlStructures/NewNonCapturingCatchSniff.php ]]; then
+            echo "::error file=.github/workflows/phpcompatibility-dev.yml,line=4,col=1::It looks like PHPCompatibility is already at version 10.0, making this Github Action obsolete. Please remove it."
+            exit 1
+          fi
+          composer remove --dev automattic/jetpack-standards
+          composer require --dev phpcompatibility/php-compatibility=dev-develop
+
+      - name: Run phpcs for PHPCompatibility
+        run: |
+          vendor/bin/phpcs -p -s --report=emacs --standard=.github/files/phpcompatibility-dev-phpcs.xml
